-- Job-Ready content depth follow-up: every one of the tier's 22 quizzes
-- (201-207 from migrations 29/30/31, 208-222 from migration 34) shipped
-- with only 4-6 questions -- below the 10-question-per-quiz bar this pass
-- sets. This adds enough additional questions to each quiz to clear that
-- bar, continuing each quiz's existing order_index sequence and grounded in
-- the same lesson content those quizzes already test (no new lessons). Each
-- new question also carries an explicit easy/medium/hard `difficulty`
-- (added by 00000000000043), rather than relying on that column's
-- 'medium' default -- a mix of recall (easy), applied reasoning (medium),
-- and worked-example arithmetic (hard) per quiz.

insert into quiz_questions (quiz_id, question, options, correct_answer, order_index, difficulty) values
  -- ===================== Interview Fundamentals (201) =====================
  ('00000000-0000-0000-0003-000000000201', 'What does a "fit" question (e.g. "why this company?") primarily reward, per the lesson?',
    '["A generic answer that could apply to any company", "Genuine, researched reasons specific to that company", "Reciting the company''s mission statement word for word", "Avoiding answering directly"]'::jsonb,
    'Genuine, researched reasons specific to that company', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000201', 'What should you do before answering an interview question well, per the lesson?',
    '["Recognize which type of question -- behavioral, technical, or fit -- it is", "Ask the interviewer to repeat the question twice", "Assume every question is behavioral", "Give the same answer you gave in your last interview"]'::jsonb,
    'Recognize which type of question -- behavioral, technical, or fit -- it is', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000201', 'What common mistake does the lesson warn against when preparing for interviews?',
    '["Preparing a few real stories for behavioral questions", "Memorising a single script and using it regardless of the question type", "Practicing concise explanations for technical concepts", "Researching the company in advance"]'::jsonb,
    'Memorising a single script and using it regardless of the question type', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000201', 'Why does a rambling personal anecdote fail as a response to a technical question, per the lesson?',
    '["Technical questions need a precise, structured explanation, not a personal story", "Personal stories are never appropriate in any interview", "Technical questions are always trick questions", "Interviewers never listen to personal anecdotes"]'::jsonb,
    'Technical questions need a precise, structured explanation, not a personal story', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000201', 'What is the core purpose of a job interview, per the lesson?',
    '["Giving the interviewer enough evidence, in a short window, to believe you can do the job and work well with the team", "Testing how well you can talk for a long time", "Finding a candidate who agrees with everything the interviewer says", "Filling a scheduled time slot"]'::jsonb,
    'Giving the interviewer enough evidence, in a short window, to believe you can do the job and work well with the team', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000201', 'In the worked example, what makes the strong answer to "tell me about a time you handled a disagreement" better than the weak one?',
    '["It uses more impressive vocabulary", "It gives one specific real situation with concrete actions and an outcome, not just a claim about yourself", "It is much longer", "It avoids mentioning the disagreement directly"]'::jsonb,
    'It gives one specific real situation with concrete actions and an outcome, not just a claim about yourself', 10, 'medium'),

  -- ===================== Resume & Behavioral Basics (202) =====================
  ('00000000-0000-0000-0003-000000000202', 'What is a resume''s primary job, per the lesson?',
    '["To describe your entire life in detail", "To get you the interview, not to describe your entire life", "To list every task you have ever performed", "To match a template exactly"]'::jsonb,
    'To get you the interview, not to describe your entire life', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000202', 'What should every resume line help a reader do, per the lesson?',
    '["Quickly see what you can do", "See how long you have worked somewhere", "Understand your personal hobbies", "Guess your salary expectations"]'::jsonb,
    'Quickly see what you can do', 6, 'easy'),
  ('00000000-0000-0000-0003-000000000202', 'What does the "R" in the STAR structure stand for?',
    '["Reason", "Review", "Result", "Recommendation"]'::jsonb,
    'Result', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000202', 'What does the lesson say ideally accompanies the Result in a STAR answer?',
    '["A number or clear before/after outcome", "A list of everyone else who was involved", "An apology for the situation", "A restatement of the Situation"]'::jsonb,
    'A number or clear before/after outcome', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000202', 'What kind of resume bullet does the lesson identify as weakest?',
    '["One that includes a measurable result", "One that just lists a responsibility with no evidence of impact", "One that mentions a team size", "One that mentions a deadline"]'::jsonb,
    'One that just lists a responsibility with no evidence of impact', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000202', 'What does STAR keep a behavioral answer from doing, per the lesson?',
    '["Being too specific", "Trailing off into vague generalities", "Mentioning any numbers", "Being memorable"]'::jsonb,
    'Trailing off into vague generalities', 10, 'medium'),

  -- ===================== Case-Method Basics (203) =====================
  ('00000000-0000-0000-0003-000000000203', 'What kind of problem does a case-method interview typically present, per the lesson?',
    '["A trivia question with one memorised correct answer", "An open-ended business problem", "A pure math exam question", "A yes/no question about the company"]'::jsonb,
    'An open-ended business problem', 6, 'easy'),
  ('00000000-0000-0000-0003-000000000203', 'Per the lesson''s recommended structure, what comes right after clarifying and restating the question?',
    '["Immediately stating a final number", "Breaking the problem into a small number of clear components", "Asking the interviewer for the answer", "Ending the interview"]'::jsonb,
    'Breaking the problem into a small number of clear components', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000203', 'Why does the lesson say you should state your assumptions "out loud"?',
    '["So the interviewer can follow and evaluate your reasoning, not just your final number", "Because silent assumptions are against the rules", "It has no real purpose", "So you can change them later without anyone noticing"]'::jsonb,
    'So the interviewer can follow and evaluate your reasoning, not just your final number', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000203', 'Using the lesson''s coffee-shop assumptions (30% of the population drinks coffee, averaging 1.2 coffees/day) on a city of 2,000,000 people, roughly how many coffees are sold per day?',
    '["360,000", "600,000", "720,000", "900,000"]'::jsonb,
    '720,000', 9, 'hard'),
  ('00000000-0000-0000-0003-000000000203', 'What is a case-method interview explicitly NOT testing, per the lesson?',
    '["Structured thinking under uncertainty", "Whether you can guess the interviewer''s expected exact answer immediately", "Whether you can state clear assumptions", "Whether you can reason step by step"]'::jsonb,
    'Whether you can guess the interviewer''s expected exact answer immediately', 10, 'easy'),

  -- ===================== Technical Interview Prep (204) =====================
  ('00000000-0000-0000-0003-000000000204', 'What are the three recurring technical-question themes named in the lesson?',
    '["Valuation, accounting/statement linkage, and markets basics", "History, geography, and current events", "Salary, benefits, and vacation policy", "Grammar, spelling, and punctuation"]'::jsonb,
    'Valuation, accounting/statement linkage, and markets basics', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000204', 'What happens to bond prices when interest rates rise, per the lesson''s anchor explanation?',
    '["They rise", "They fall -- there is an inverse relationship", "They stay exactly the same", "They become impossible to value"]'::jsonb,
    'They fall -- there is an inverse relationship', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000204', 'What is the purpose of practicing anchor explanations "out loud," not just reading them, per the lesson?',
    '["It prevents freezing when asked to explain live under pressure", "It has no real effect on interview performance", "It is required by most interviewers", "It replaces the need to understand the underlying concept"]'::jsonb,
    'It prevents freezing when asked to explain live under pressure', 9, 'medium'),
  ('00000000-0000-0000-0003-000000000204', 'In the worked example (depreciation up £10, 25% tax rate), what is the net effect on total assets?',
    '["Assets rise by £10", "Assets fall by £7.50 net (cash +£2.50, fixed assets -£10)", "Assets are unaffected", "Assets fall by £10"]'::jsonb,
    'Assets fall by £7.50 net (cash +£2.50, fixed assets -£10)', 10, 'hard'),

  -- ===================== Market Sizing & Case Interviews (205) =====================
  ('00000000-0000-0000-0003-000000000205', 'What general structure does this lesson say Case-Method Basics already covered?',
    '["The clarify, break down, assume, calculate, sanity-check process", "A fixed script to memorise for every case", "A rule requiring you to always guess low", "A requirement to never state assumptions"]'::jsonb,
    'The clarify, break down, assume, calculate, sanity-check process', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000205', 'In the bank-branch worked example, what average annual revenue per account is assumed?',
    '["£80", "£120", "£150", "£200"]'::jsonb,
    '£120', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000205', 'Why is a finance-flavored case interviewer also watching your structure, not just your final number, per the lesson?',
    '["Because they want to see whether your structure would actually support a real recommendation", "Because the final number is never checked", "Because structure is only relevant for non-finance cases", "Because interviewers are required to ignore the final number"]'::jsonb,
    'Because they want to see whether your structure would actually support a real recommendation', 9, 'medium'),
  ('00000000-0000-0000-0003-000000000205', 'If the branch''s capture rate were 2% instead of 4% (all else equal), what does the lesson say happens to its year-one economics?',
    '["It stays exactly break-even", "Revenue drops to £84,000 against £150,000 cost, a loss", "Revenue rises above £168,000", "Costs automatically fall to match revenue"]'::jsonb,
    'Revenue drops to £84,000 against £150,000 cost, a loss', 10, 'hard'),

  -- ===================== Ethics & Compliance in Finance (206) =====================
  ('00000000-0000-0000-0003-000000000206', 'What is a conflict of interest, per the lesson?',
    '["A situation where your interests, or your firm''s, could improperly influence advice given to a client", "Any disagreement between two coworkers", "A legal requirement to disclose your salary", "A type of insider trading"]'::jsonb,
    'A situation where your interests, or your firm''s, could improperly influence advice given to a client', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000206', 'Why do interviewers, especially at banks, often ask an ethics/compliance-flavored question, per the lesson?',
    '["To see how a candidate reasons about the issue, not to test memorised rules", "Because it is required by law to ask this exact question", "To eliminate every candidate who answers at all", "Because ethics questions have no real answer"]'::jsonb,
    'To see how a candidate reasons about the issue, not to test memorised rules', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000206', 'What three concepts does the lesson say come up repeatedly in finance ethics questions?',
    '["Conflicts of interest, insider trading, and fiduciary duty", "Marketing, sales, and advertising", "Hiring, firing, and promotion", "Budgeting, saving, and investing"]'::jsonb,
    'Conflicts of interest, insider trading, and fiduciary duty', 9, 'medium'),
  ('00000000-0000-0000-0003-000000000206', 'Why does the lesson say deciding alone and acting quickly is generally the wrong move in a gray-area ethics situation?',
    '["Because escalating to compliance or a manager is the safer default in a regulated industry", "Because acting quickly is always illegal", "Because gray-area situations never actually occur", "Because only senior staff are allowed opinions"]'::jsonb,
    'Because escalating to compliance or a manager is the safer default in a regulated industry', 10, 'hard'),

  -- ===================== Advanced Behavioral: Leadership, Failure & Conflict (207) =====================
  ('00000000-0000-0000-0003-000000000207', 'What does STARL add on top of the STAR structure, per the lesson?',
    '["A second Situation", "Learning -- a concrete statement of what you do differently now", "A list of every team member''s name", "A restatement of the Task"]'::jsonb,
    'Learning -- a concrete statement of what you do differently now', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000207', 'Per the lesson, what are the two most common ways candidates answer failure questions badly?',
    '["Picking a disguised strength, or stopping at the mistake without showing what changed", "Speaking too quietly and too slowly", "Refusing to answer entirely", "Giving too many examples at once"]'::jsonb,
    'Picking a disguised strength, or stopping at the mistake without showing what changed', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000207', 'What does a conflict behavioral question specifically test, distinct from a leadership question, per the lesson?',
    '["Whether you can resolve tension productively without becoming a pushover or combative", "Whether you have ever led a formal team", "Whether you avoid all workplace disagreement", "Whether you always win every argument"]'::jsonb,
    'Whether you can resolve tension productively without becoming a pushover or combative', 9, 'medium'),
  ('00000000-0000-0000-0003-000000000207', 'In the STARL worked example, what specific ongoing behavior change did the candidate describe?',
    '["Never working in groups again", "Asking each teammate to restate their part back and checking in at the halfway point", "Always doing every part of a group project alone", "Assigning someone else to check in instead"]'::jsonb,
    'Asking each teammate to restate their part back and checking in at the halfway point', 10, 'hard'),

  -- ===================== Negotiating a Job Offer (208) =====================
  ('00000000-0000-0000-0003-000000000208', 'What tone does the lesson recommend when making a counter-offer?',
    '["Polite and enthusiastic, while still naming a specific number", "Apologetic about asking for more", "Firm and confrontational", "Vague, to avoid committing to a number"]'::jsonb,
    'Polite and enthusiastic, while still naming a specific number', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000208', 'In the worked example, what number does the candidate counter with, and why?',
    '["$62,000, the original offer", "$70,000, the very top of any range", "$68,000, grounded in the stated $60,000-$70,000 market range", "$100,000, an arbitrary round number"]'::jsonb,
    '$68,000, grounded in the stated $60,000-$70,000 market range', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000208', 'What sources does the lesson suggest for researching a realistic market range?',
    '["Published salary surveys, professional networks, or ranges companies may be required to disclose", "Guessing based on rent prices in the area", "Asking a stranger on the street", "Only the company''s own recruiter"]'::jsonb,
    'Published salary surveys, professional networks, or ranges companies may be required to disclose', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000208', 'What does declining to negotiate at all typically mean, per the lesson?',
    '["Leaving value on the table that the employer had already budgeted for", "Guaranteeing the best possible offer", "Signaling strong negotiating skill", "Having no effect on the final offer either way"]'::jsonb,
    'Leaving value on the table that the employer had already budgeted for', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000208', 'Which of these is explicitly named by the lesson as negotiable besides base salary?',
    '["The interviewer''s personal schedule", "Signing bonus", "The company''s stock price", "The company''s holiday calendar for all staff"]'::jsonb,
    'Signing bonus', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000208', 'Why is asking for "as much as possible" with no anchor considered a weak approach, per the lesson?',
    '["It is illegal in most jurisdictions", "It isn''t a specific, defensible number grounded in research", "It always results in a lower offer", "Employers are required to reject it"]'::jsonb,
    'It isn''t a specific, defensible number grounded in research', 10, 'medium'),

  -- ===================== Understanding Your Compensation Package (209) =====================
  ('00000000-0000-0000-0003-000000000209', 'Which compensation component is described as "fixed, predictable pay," per the lesson?',
    '["Bonus", "Equity", "Base salary", "Benefits"]'::jsonb,
    'Base salary', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000209', 'Why can comparing two offers by base salary alone be misleading, per the lesson?',
    '["Because base salary is always identical across companies", "Because their other components (bonus, equity, benefits) may differ substantially", "Because base salary is not actually part of compensation", "Because only the highest base salary ever matters"]'::jsonb,
    'Because their other components (bonus, equity, benefits) may differ substantially', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000209', 'What kind of value does a benefit like employer-paid health insurance carry, per the lesson, even though it isn''t cash?',
    '["No value at all", "Real monetary value comparable to what it would cost to buy individually", "Only symbolic value", "Negative value, since it reduces take-home pay"]'::jsonb,
    'Real monetary value comparable to what it would cost to buy individually', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000209', 'In the worked example, roughly how much is Offer B''s employer-paid health insurance worth per year?',
    '["Roughly $600", "Roughly $6,000", "Roughly $16,000", "Roughly $60,000"]'::jsonb,
    'Roughly $6,000', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000209', 'What determines whether a bonus target is actually paid out in full, per the lesson?',
    '["Hitting performance targets, which aren''t fully in your control", "The employee''s tenure alone", "Whether the bonus is mentioned in the offer letter", "Nothing -- bonus targets are always paid in full"]'::jsonb,
    'Hitting performance targets, which aren''t fully in your control', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000209', 'What is the lesson''s overall recommendation when comparing job offers?',
    '["Compare total package value, not just base salary", "Only ever compare base salary", "Ignore benefits entirely", "Always take the offer with the highest signing bonus"]'::jsonb,
    'Compare total package value, not just base salary', 10, 'medium'),

  -- ===================== Reading a Pay Stub & Taxes (210) =====================
  ('00000000-0000-0000-0003-000000000210', 'What are voluntary deductions, per the lesson?',
    '["Deductions you elected yourself, like retirement contributions or a share of health premiums", "Deductions required by federal law with no exceptions", "A synonym for gross pay", "Deductions taken only from bonus pay"]'::jsonb,
    'Deductions you elected yourself, like retirement contributions or a share of health premiums', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000210', 'What life changes does the lesson say can affect how much tax should be withheld going forward?',
    '["A raise, a second job, or marriage", "Changing your commute route", "Moving to a new desk at the same job", "Getting a new phone number"]'::jsonb,
    'A raise, a second job, or marriage', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000210', 'What happens if too much tax was withheld across the year, per the lesson?',
    '["You owe an additional penalty", "You get a refund", "Nothing changes at tax-filing time", "Your employer keeps the difference"]'::jsonb,
    'You get a refund', 7, 'easy'),
  ('00000000-0000-0000-0003-000000000210', 'In the worked example, what is the total of federal, payroll, and state tax withheld (before the voluntary 401(k) deduction)?',
    '["$505", "$585", "$630", "$755"]'::jsonb,
    '$585', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000210', 'What is a W-4, per the lesson''s US-context example?',
    '["A form of ID required to start a job", "Information you provide that determines estimated tax withholding", "A tax refund check", "A retirement account statement"]'::jsonb,
    'Information you provide that determines estimated tax withholding', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000210', 'Why does the lesson say someone who budgets against their quoted salary will "consistently overspend"?',
    '["Because deductions mean actual net pay is meaningfully less than the gross figure", "Because quoted salaries are usually inflated by employers", "Because net pay is always higher than gross pay", "Because budgeting is unrelated to pay stubs"]'::jsonb,
    'Because deductions mean actual net pay is meaningfully less than the gross figure', 10, 'medium'),

  -- ===================== Employer Retirement Matching (211) =====================
  ('00000000-0000-0000-0003-000000000211', 'What US retirement plan does the lesson use as its main example?',
    '["A 401(k)", "A Roth IRA only", "A pension with no employee contribution", "A health savings account"]'::jsonb,
    'A 401(k)', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000211', 'What does "matching 50% of your contribution, up to 6% of your salary" mean, per the lesson?',
    '["The employer pays your full salary in retirement contributions", "The employer adds 50 cents for every dollar you contribute, up to a contribution of 6% of salary", "You must contribute exactly 50% of your salary", "The employer only matches after 6 years of employment"]'::jsonb,
    'The employer adds 50 cents for every dollar you contribute, up to a contribution of 6% of salary', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000211', 'Contributions in these retirement accounts usually grow how, per the lesson?',
    '["Tax-advantaged, without being taxed each year the way ordinary account gains might be", "Fully taxed every year at the highest rate", "Only in cash with no growth at all", "Exactly the same as a regular checking account"]'::jsonb,
    'Tax-advantaged, without being taxed each year the way ordinary account gains might be', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000211', 'Priya earns $50,000/year with a 50%-match-up-to-6% plan. If she contributes 4% instead of the full 6%, how much employer match does she receive?',
    '["$1,500", "$1,000", "$2,000", "$500"]'::jsonb,
    '$1,000', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000211', 'What does the lesson call skipping a full employer retirement match?',
    '["A smart, risk-free choice", "Leaving free money -- guaranteed extra pay -- on the table", "A legal requirement for new employees", "Something with no real cost either way"]'::jsonb,
    'Leaving free money -- guaranteed extra pay -- on the table', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000211', 'Why does the lesson say to check your own plan''s specific match formula rather than assume a standard one?',
    '["Because match formulas vary by employer, and the plan''s actual terms determine how much you should contribute to capture it fully", "Because all plans are legally required to be identical", "Because match formulas never affect take-home pay", "Because checking the formula is optional and has no real benefit"]'::jsonb,
    'Because match formulas vary by employer, and the plan''s actual terms determine how much you should contribute to capture it fully', 10, 'medium'),

  -- ===================== Health Insurance Basics (212) =====================
  ('00000000-0000-0000-0003-000000000212', 'What is a premium, per the lesson?',
    '["What you must pay out of pocket before insurance covers a larger share", "What you pay regularly, usually deducted from each paycheck, regardless of whether you use care", "A one-time signup fee", "A tax withheld from your paycheck"]'::jsonb,
    'What you pay regularly, usually deducted from each paycheck, regardless of whether you use care', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000212', 'What is a deductible, per the lesson?',
    '["What you must pay out of pocket for care before insurance starts covering a larger share", "A monthly fee paid regardless of care used", "A synonym for premium", "A tax credit for buying insurance"]'::jsonb,
    'What you must pay out of pocket for care before insurance starts covering a larger share', 6, 'easy'),
  ('00000000-0000-0000-0003-000000000212', 'Who might prefer a low-premium, high-deductible plan, per the lesson?',
    '["Someone who rarely needs medical care and wants to minimize guaranteed monthly cost", "Someone who expects frequent, ongoing medical care", "Someone who wants the lowest possible deductible", "Someone with no interest in cost at all"]'::jsonb,
    'Someone who rarely needs medical care and wants to minimize guaranteed monthly cost', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000212', 'In the worked example, what is Plan A''s total cost (premiums + deductible) if a $4,000 medical expense occurs?',
    '["$600", "$1,800", "$3,000", "$3,600"]'::jsonb,
    '$3,600', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000212', 'What is the general relationship between premium and deductible across health plans, per the lesson?',
    '["They always move in the same direction", "Lower premium typically means higher deductible, and vice versa", "They are set independently with no typical pattern", "Deductibles are fixed by law and never vary"]'::jsonb,
    'Lower premium typically means higher deductible, and vice versa', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000212', 'What should ultimately determine which health plan is the "right" choice for a given person, per the lesson?',
    '["Always the lowest premium available", "How much medical care you realistically expect to use in a given year", "Whichever plan a coworker picked", "Always the lowest deductible available"]'::jsonb,
    'How much medical care you realistically expect to use in a given year', 10, 'medium'),

  -- ===================== Workplace Financial Etiquette (213) =====================
  ('00000000-0000-0000-0003-000000000213', 'What is generally required to submit a proper expense report, per the lesson?',
    '["An itemized receipt, a stated business purpose, and timely submission", "Just a verbal request to a manager", "Nothing -- all expenses are automatically reimbursed", "Only a credit card statement total"]'::jsonb,
    'An itemized receipt, a stated business purpose, and timely submission', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000213', 'What does a per diem replace the need for, per the lesson?',
    '["Itemized receipts for every small purchase like meals during travel", "Any kind of expense reporting at all", "A manager''s approval", "A stated business purpose"]'::jsonb,
    'Itemized receipts for every small purchase like meals during travel', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000213', 'Is it acceptable to treat a generous per diem as personal spending money, per the lesson?',
    '["Yes, per diems are unrestricted personal funds", "No, spending is still expected to stay reasonable and business-related", "Yes, as long as no receipts are requested", "Only during international travel"]'::jsonb,
    'No, spending is still expected to stay reasonable and business-related', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000213', 'In the worked example, what specifically made the vague expense submission problematic?',
    '["It was for too small a dollar amount", "No receipts, no clear business purpose, and submission six weeks late", "It was submitted using the wrong software", "It included too much detail"]'::jsonb,
    'No receipts, no clear business purpose, and submission six weeks late', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000213', 'What is commonly required alongside a credit card statement total for reimbursement, per the lesson?',
    '["Nothing further is ever required", "An itemized receipt, not just the statement total", "A notarized letter", "Approval from two separate managers"]'::jsonb,
    'An itemized receipt, not just the statement total', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000213', 'What does careful, well-documented expense reporting do, per the lesson?',
    '["Guarantees a promotion", "Builds trust with a manager or finance team early in a role", "Has no effect on workplace relationships", "Automatically increases your salary"]'::jsonb,
    'Builds trust with a manager or finance team early in a role', 10, 'medium'),

  -- ===================== Budgeting on Your First Salary (214) =====================
  ('00000000-0000-0000-0003-000000000214', 'What is the first correction the lesson recommends for a first budget?',
    '["Building it around net pay, not the headline salary figure", "Spending exactly what you earn each month", "Ignoring taxes entirely", "Budgeting only once a year"]'::jsonb,
    'Building it around net pay, not the headline salary figure', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000214', 'What percentage of net pay does the 50/30/20 framework allocate to wants?',
    '["20%", "30%", "50%", "70%"]'::jsonb,
    '30%', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000214', 'On $3,200/month net pay, roughly how much does the 50/30/20 framework suggest for savings and extra debt paydown?',
    '["$320", "$480", "$640", "$960"]'::jsonb,
    '$640', 7, 'hard'),
  ('00000000-0000-0000-0003-000000000214', 'Why is 50/30/20 described as a starting benchmark rather than a rigid rule, per the lesson?',
    '["Because cost of living varies enormously by location", "Because it only applies to people over 30", "Because it is a legal requirement in some states", "Because savings percentages are fixed by law"]'::jsonb,
    'Because cost of living varies enormously by location', 8, 'medium'),
  ('00000000-0000-0000-0003-000000000214', 'What is "lifestyle inflation," per the lesson?',
    '["A government policy that raises minimum wage", "Scaling up spending immediately to match a new, larger gross salary figure", "A type of tax withholding", "An annual cost-of-living raise from an employer"]'::jsonb,
    'Scaling up spending immediately to match a new, larger gross salary figure', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000214', 'What should be decided deliberately, rather than left to whatever remains at month''s end, per the lesson?',
    '["How much of net pay goes to needs, wants, and savings", "The exact date rent is due", "Your employer''s pay schedule", "The name of your bank"]'::jsonb,
    'How much of net pay goes to needs, wants, and savings', 10, 'medium'),

  -- ===================== Building an Emergency Fund (215) =====================
  ('00000000-0000-0000-0003-000000000215', 'What kinds of expenses is an emergency fund meant to absorb, per the lesson?',
    '["Planned monthly bills like rent", "Unplanned, necessary expenses like a job loss, medical bill, or urgent car repair", "Vacations and discretionary purchases", "Retirement contributions"]'::jsonb,
    'Unplanned, necessary expenses like a job loss, medical bill, or urgent car repair', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000215', 'Why is an emergency fund kept separate from everyday spending and other savings goals, per the lesson?',
    '["So it isn''t accidentally spent on something else", "Because banks require separate accounts by law", "So it can be invested more aggressively", "Because it earns a different interest rate automatically"]'::jsonb,
    'So it isn''t accidentally spent on something else', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000215', 'What commonly cited target range does the lesson give for an emergency fund?',
    '["1-2 weeks of essential expenses", "3-6 months of essential expenses", "1-2 years of full income", "A fixed $10,000 for everyone"]'::jsonb,
    '3-6 months of essential expenses', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000215', 'In the worked example, saving $200/month starting from $0, roughly how long does it take to reach the 6-month target of $10,800?',
    '["27 months", "36 months", "54 months", "90 months"]'::jsonb,
    '54 months', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000215', 'What determines whether someone should target the lower or higher end of the 3-6 month range, per the lesson?',
    '["Job stability and other safety nets", "The current stock market''s performance", "Their employer''s size", "How much they enjoy saving money"]'::jsonb,
    'Job stability and other safety nets', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000215', 'Why does the lesson recommend keeping an emergency fund in something accessible and low-risk rather than invested?',
    '["So it isn''t at risk of losing value right when it''s needed", "Because investing is illegal for personal savings", "Because low-risk accounts always outperform investments", "Because emergency funds are never actually used"]'::jsonb,
    'So it isn''t at risk of losing value right when it''s needed', 10, 'medium'),

  -- ===================== Startup Equity & Stock Options (216) =====================
  ('00000000-0000-0000-0003-000000000216', 'What is a strike price, per the lesson?',
    '["The current public market price of a stock", "The fixed price set now at which you can later buy company shares", "A fee charged for exercising options", "The company''s annual revenue"]'::jsonb,
    'The fixed price set now at which you can later buy company shares', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000216', 'What does "dilution" mean, per the lesson?',
    '["Your number of shares automatically decreases over time", "As a startup issues more shares in later funding rounds, each existing share represents a smaller percentage of the company", "Options become worth more as more shares are issued", "A company reducing its total valuation"]'::jsonb,
    'As a startup issues more shares in later funding rounds, each existing share represents a smaller percentage of the company', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000216', 'What is a common vesting schedule structure named in the lesson?',
    '["4 years with a 1-year cliff", "1 year with no cliff", "10 years with no cliff", "Immediate vesting on the first day"]'::jsonb,
    '4 years with a 1-year cliff', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000216', 'In the worked example, what is the pre-tax value of 10,000 vested options at a $1 strike price if shares are later worth $5 each?',
    '["$10,000", "$40,000", "$50,000", "$60,000"]'::jsonb,
    '$40,000', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000216', 'Why do startups sometimes offer equity as part of a compensation package, per the lesson?',
    '["Because cash salary is often lower than at an established company", "Because it is required by law for all startups", "Because equity always guarantees higher total pay", "Because cash compensation is illegal at startups"]'::jsonb,
    'Because cash salary is often lower than at an established company', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000216', 'Why does the lesson recommend treating startup equity as speculative upside rather than a cash substitute?',
    '["Because most startups fail or are acquired for modest amounts, so most employee equity ends up worth little or nothing", "Because equity is always worth more than cash", "Because equity cannot legally be included in an offer", "Because options vest immediately with no risk"]'::jsonb,
    'Because most startups fail or are acquired for modest amounts, so most employee equity ends up worth little or nothing', 10, 'medium'),

  -- ===================== Professional Networking Basics (217) =====================
  ('00000000-0000-0000-0003-000000000217', 'What does the lesson identify as the lowest-pressure, most effective form of networking for someone early in their career?',
    '["The informational interview", "Cold-calling company executives", "Mass-messaging as many strangers as possible", "Attending only large public job fairs"]'::jsonb,
    'The informational interview', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000217', 'What does an informational interview explicitly NOT ask for, per the lesson?',
    '["Someone''s perspective on their field", "A job", "15 minutes of someone''s time", "Advice on a career path"]'::jsonb,
    'A job', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000217', 'Why does an informational interview cost the other person "little," per the lesson?',
    '["Because it doesn''t put them on the spot to make a hiring decision", "Because it is always shorter than 5 minutes", "Because it is anonymous", "Because it requires no response at all"]'::jsonb,
    'Because it doesn''t put them on the spot to make a hiring decision', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000217', 'In the worked example outreach message, what three qualities make it effective, per the lesson?',
    '["Long, formal, and generic", "Specific, time-bounded, and low-pressure", "Vague, urgent, and demanding", "Anonymous, brief, and impersonal"]'::jsonb,
    'Specific, time-bounded, and low-pressure', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000217', 'What keeps a networking relationship "genuinely alive," per the lesson?',
    '["Only reaching out when you need something", "Following up and staying in touch over time", "Sending the same message to everyone once", "Never contacting the person again after the first meeting"]'::jsonb,
    'Following up and staying in touch over time', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000217', 'Why does the lesson warn against every message to a contact feeling like a "one-off ask"?',
    '["Because it prevents building a genuine, ongoing professional relationship", "Because one-off messages are against LinkedIn''s rules", "Because it makes messages too short", "Because contacts expect a new ask every single time"]'::jsonb,
    'Because it prevents building a genuine, ongoing professional relationship', 10, 'medium'),

  -- ===================== Personal Branding & LinkedIn Basics (218) =====================
  ('00000000-0000-0000-0003-000000000218', 'What does the lesson identify as the highest-leverage piece of an early-career professional''s public presence?',
    '["A personal website", "LinkedIn", "A physical business card", "A printed resume alone"]'::jsonb,
    'LinkedIn', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000218', 'What should a strong LinkedIn headline state, beyond just a job title, per the lesson?',
    '["What you actually do or are looking for", "Your exact salary expectations", "Your home address", "A list of every course you have taken"]'::jsonb,
    'What you actually do or are looking for', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000218', 'How should a LinkedIn summary be written, per the lesson?',
    '["As a bare list of skills with no context", "In your own voice, stating background and goals", "Copy-pasted from a template with no changes", "As short as physically possible, with zero detail"]'::jsonb,
    'In your own voice, stating background and goals', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000218', 'Why does the lesson warn against copy-pasting official job descriptions into LinkedIn experience entries?',
    '["Because job descriptions are copyrighted and cannot legally be referenced", "Because entries should follow the same context/action/result pattern as strong resume bullets", "Because LinkedIn automatically deletes copied text", "Because experience entries are optional and rarely read"]'::jsonb,
    'Because entries should follow the same context/action/result pattern as strong resume bullets', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000218', 'What does the lesson call the consistent impression your public professional presence creates?',
    '["A resume summary", "A personal brand", "A cover letter", "A reference list"]'::jsonb,
    'A personal brand', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000218', 'Why does consistency across resume, LinkedIn, and interview story matter, per the lesson?',
    '["Discrepancies (mismatched dates, different framings) are a quiet red flag to anyone checking closely", "LinkedIn automatically flags any inconsistency to employers", "Consistency is legally required for all job applicants", "It has no real effect on how a candidate is perceived"]'::jsonb,
    'Discrepancies (mismatched dates, different framings) are a quiet red flag to anyone checking closely', 10, 'medium'),

  -- ===================== Benefits Enrollment (219) =====================
  ('00000000-0000-0000-0003-000000000219', 'What is open enrollment, per the lesson?',
    '["A one-time signup available only to new hires", "A defined annual window to choose or change benefit elections", "An ongoing process available at any time of year", "A window for negotiating base salary"]'::jsonb,
    'A defined annual window to choose or change benefit elections', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000219', 'What can allow a benefit election change outside the open enrollment window, per the lesson?',
    '["A qualifying life event, like marriage or a new child", "Simply asking HR at any time", "Nothing -- elections can never change outside the window", "Changing job titles within the same company"]'::jsonb,
    'A qualifying life event, like marriage or a new child', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000219', 'What is an HSA typically available alongside, per the lesson?',
    '["Any health plan, with no restrictions", "Certain high-deductible health plans", "Only employer-paid plans with no premium", "Dental insurance exclusively"]'::jsonb,
    'Certain high-deductible health plans', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000219', 'In the worked example, how much of a $2,000 HSA contribution rolls over if only $600 is used that year?',
    '["$0", "$600", "$1,400", "$2,000"]'::jsonb,
    '$1,400', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000219', 'What does "use it or lose it" describe, per the lesson?',
    '["An HSA''s permanent, rolling-over balance", "A standard FSA''s typical rule that unused balance is forfeited at year-end", "A rule that applies to base salary", "A rule requiring immediate spending of any bonus"]'::jsonb,
    'A standard FSA''s typical rule that unused balance is forfeited at year-end', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000219', 'Why does the lesson recommend understanding benefit choices before the enrollment window, not during it?',
    '["Because most elections are locked in for a full year absent a qualifying life event", "Because the window is only open for one hour each year", "Because benefits information disappears once the window opens", "Because elections made during the window are non-binding anyway"]'::jsonb,
    'Because most elections are locked in for a full year absent a qualifying life event', 10, 'medium'),

  -- ===================== Credit Cards & Building Credit (220) =====================
  ('00000000-0000-0000-0003-000000000220', 'What does a credit score summarize, per the lesson?',
    '["Your total account balance across all banks", "How reliably you have repaid borrowed money in the past", "Your annual income", "Your employer''s credit rating"]'::jsonb,
    'How reliably you have repaid borrowed money in the past', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000220', 'Besides credit approvals, what else can a credit score influence, per the lesson?',
    '["Apartment applications and car loan interest rates", "Your eligibility to vote", "Your passport renewal", "Your employer''s stock price"]'::jsonb,
    'Apartment applications and car loan interest rates', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000220', 'What happens if you carry a credit card balance instead of paying it in full, per the lesson?',
    '["Nothing -- there is no cost to carrying a balance", "You typically pay interest, often 20%+ APR, on top of the underlying debt", "Your credit limit is automatically reduced to zero", "Your credit score always improves"]'::jsonb,
    'You typically pay interest, often 20%+ APR, on top of the underlying debt', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000220', 'What is "credit utilization," per the lesson?',
    '["The number of credit cards you own", "The share of your available credit limit you are actually using", "The interest rate charged on a loan", "The number of years you have had credit"]'::jsonb,
    'The share of your available credit limit you are actually using', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000220', 'What does the lesson identify as typically the single most damaging action to a credit score?',
    '["Having a high credit limit", "Missing a payment, even by a few days", "Opening a first credit card at all", "Using a credit card for everyday purchases"]'::jsonb,
    'Missing a payment, even by a few days', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000220', 'In the worked example, how can spreading spending more evenly across the month help, even without changing total spending?',
    '["It keeps reported utilization lower at the moment the issuer reports the balance", "It automatically lowers the interest rate charged", "It increases the credit limit", "It has no effect on the score at all"]'::jsonb,
    'It keeps reported utilization lower at the moment the issuer reports the balance', 10, 'medium'),

  -- ===================== Student Loan Repayment Basics (221) =====================
  ('00000000-0000-0000-0003-000000000221', 'How long is a typical loan grace period after graduation, per the lesson?',
    '["Around 6 months", "Around 2 weeks", "Around 5 years", "There is no grace period"]'::jsonb,
    'Around 6 months', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000221', 'What do federal loans generally offer that private loans typically do not, per the lesson?',
    '["More repayment plan options, including income-driven plans in some cases", "A guaranteed lower interest rate in all cases", "Automatic forgiveness after one year", "No grace period at all"]'::jsonb,
    'More repayment plan options, including income-driven plans in some cases', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000221', 'What does a standard repayment plan set, per the lesson?',
    '["A fixed monthly payment over a fixed period, often 10 years", "A payment that changes every month at random", "No monthly payment until the balance is due in full", "A payment based only on discretionary income"]'::jsonb,
    'A fixed monthly payment over a fixed period, often 10 years', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000221', 'In the worked example, roughly what is the fixed monthly payment on a $30,000 loan at 5% interest over a standard 10-year plan?',
    '["Roughly $150", "Roughly $320", "Roughly $500", "Roughly $1,000"]'::jsonb,
    'Roughly $320', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000221', 'What does an income-driven repayment plan set the payment as, per the lesson?',
    '["A fixed dollar amount for everyone", "A percentage of discretionary income", "A percentage of total loan balance paid upfront", "Whatever amount the lender chooses randomly"]'::jsonb,
    'A percentage of discretionary income', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000221', 'What is the main trade-off of an income-driven plan compared to a standard plan, per the lesson?',
    '["It has no trade-off -- it is strictly better in every way", "Lower near-term payments, but usually a longer repayment period and more total interest paid", "Higher near-term payments but a shorter repayment period", "It is only available for private loans"]'::jsonb,
    'Lower near-term payments, but usually a longer repayment period and more total interest paid', 10, 'medium'),

  -- ===================== Workplace Communication & Professionalism (222) =====================
  ('00000000-0000-0000-0003-000000000222', 'Why are workplace communication norms easy to get wrong early in a career, per the lesson?',
    '["They are usually never explicitly taught", "They are identical at every company", "They are written into every employee handbook in detail", "They never change between workplaces"]'::jsonb,
    'They are usually never explicitly taught', 5, 'easy'),
  ('00000000-0000-0000-0003-000000000222', 'What is the lesson''s recommended default for norms like response speed and channel choice?',
    '["Matching the tone and channel your current team already uses", "Always using the most formal channel available", "Copying exactly what your previous school or internship did", "Ignoring norms entirely and doing whatever feels natural"]'::jsonb,
    'Matching the tone and channel your current team already uses', 6, 'medium'),
  ('00000000-0000-0000-0003-000000000222', 'Where should a disagreement with a manager''s decision generally be raised first, per the lesson?',
    '["In a large team meeting for visibility", "Privately, with the relevant person", "Anonymously through a suggestion box", "Never -- disagreements should not be raised at all"]'::jsonb,
    'Privately, with the relevant person', 7, 'medium'),
  ('00000000-0000-0000-0003-000000000222', 'In the worked example, what made the stronger response to a disagreement effective, per the lesson?',
    '["It avoided stating any actual concern", "It raised a clear, reasoned concern privately and offered to help rather than just criticize", "It was delivered in a team meeting for visibility", "It simply agreed with the manager regardless of the concern"]'::jsonb,
    'It raised a clear, reasoned concern privately and offered to help rather than just criticize', 8, 'hard'),
  ('00000000-0000-0000-0003-000000000222', 'What does the lesson warn against assuming transfers directly between workplaces?',
    '["Communication norms from school or a previous internship", "Your job title", "Your salary expectations", "Your resume format"]'::jsonb,
    'Communication norms from school or a previous internship', 9, 'easy'),
  ('00000000-0000-0000-0003-000000000222', 'Why does raising a disagreement in a group setting tend to be worse than raising it privately first, per the lesson?',
    '["It is more likely to read as combative and can damage the relationship even when the concern is valid", "Group settings are against company policy everywhere", "Managers never respond in group settings", "It takes longer to raise a concern privately"]'::jsonb,
    'It is more likely to read as combative and can damage the relationship even when the concern is valid', 10, 'medium');
